server:
  port: 7003
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: helloworld-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud