server:
  port: 7003
zuul:
  routes:
    helloworld-service:
      path: /v1/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud